//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMAUTO1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factures
    {
        public string idfacture { get; set; }
        public string cin { get; set; }
        public int Montant { get; set; }
        public string modele { get; set; }
        public string categorie { get; set; }
        public string Contrats_idcontrat { get; set; }
        public Nullable<System.DateTime> datefactures { get; set; }
    }
}
